### ISSUE TITLE
Not in english

### ISSUE THREAD

**Issue by vampiregoat699** [XiaMoZhiShi/FeatherMorphClient#2]
Looks cool but nothing is in english so have NO idea what anything says

**Comment by MATRIX-feather** [comment]
I can't reproduce it... Have you checked your language setting? And which version of Minecraft and the mod do you use?

**Comment by MATRIX-feather** [comment]
If you mean the README file, you can use a translator like Google and DeepL.

I don't plan to make an English README on Github in short term, as there is already an English introduction on Modrinth.
